#!/usr/bin/env python3
"""Generate training data targeted at the measured FP and FN mechanisms.

FP side (19 of 26 reachable), synthesised because mining cannot reach it:
  the distractor in these errors is usually NOT a candidate taxon ("fish and
  other ectotherms", "gut metagenome", "temperature of fruit"), so no amount of
  co-occurrence mining produces the negative. We build it from the sentence:
  take a verified positive (X, r, Y) and re-target the relation at a DIFFERENT
  taxon mentioned in the same passage. The teacher then adjudicates, so we add
  supervision rather than noise.

FN side (the handoff's 11 rejects): topic-shifted, nominalised, high-rank.
  These are phrasing gaps, not topic gaps, so they are generated by rewriting
  verified positives into the missing surface forms and re-verifying.
"""
import ast, json, re, sys
from pathlib import Path
import numpy as np, pandas as pd

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO/"src"))
SEED = 20260921
rng = np.random.RandomState(SEED)

def norm(s): return " ".join(str(s).split()).strip()
def first(x):
    if isinstance(x,(list,np.ndarray)): return str(x[0]).strip() if len(x) else ""
    s=str(x)
    if s.startswith("["):
        try:
            v=ast.literal_eval(s); return str(v[0]) if isinstance(v,list) and v else s
        except Exception: return s.strip("[]'\" ")
    return s.strip() if pd.notna(x) else ""

# ── benchmark guards ──────────────────────────────────────────────────────
btxt,bpair=set(),set()
for f,tc,kw,pc in [("data/evaluation/biotic_interaction_test_set.csv","sentence",{},None),
                   ("data/evaluation/test500_paired.csv","sentence",{},("species1","species2")),
                   ("data/evaluation/biotx_rejected_50_testset.csv","sentence",{},None),
                   ("globi-relax_passages-triplets_2024-02-28_curation_EP.tsv","sentence",dict(sep="\t",encoding="latin-1"),("species1_term","species2_term")),
                   ("data/evaluation/biotx_retrieval_eval_100.csv","sentence",dict(sep=";",encoding="utf-8-sig"),("species1_term","species2_term"))]:
    p=REPO/f
    if not p.exists(): continue
    x=pd.read_csv(p,**kw)
    if tc in x.columns: btxt |= set(x[tc].astype(str).map(norm))
    if pc and pc[0] in x.columns:
        bpair |= {tuple(sorted([norm(a).lower(),norm(b).lower()])) for a,b in zip(x[pc[0]],x[pc[1]]) if pd.notna(a) and pd.notna(b)}
print(f"guards: {len(btxt)} benchmark passages, {len(bpair)} benchmark pairs")

pool=pd.read_parquet(REPO/"data/training/distill/med25_pool.parquet")
for c in ("species1_form","species2_form","interaction_form"): pool[c]=pool[c].map(first)
pool["passage"]=pool.passage.map(norm)
pool=pool[(pool.species1_form!="")&(pool.species2_form!="")&(pool.interaction_form!="")]
pool["pk"]=[tuple(sorted([a.lower(),b.lower()])) for a,b in zip(pool.species1_form,pool.species2_form)]
pool=pool[~pool.passage.isin(btxt) & ~pool.pk.isin(bpair)]

# ── D: DISTRACTOR negatives — re-target a verified relation at a third taxon ──
# Build a taxon vocabulary from the pool itself, then find taxa that appear in a
# passage but are NOT the queried pair.
vocab = pd.concat([pool.species1_form, pool.species2_form]).value_counts()
vocab = vocab[(vocab >= 5)]                    # seen enough to be a real surface form
vocab = [v for v in vocab.index if len(v) >= 4 and not v.islower() or len(v.split())>1]
vocab_lc = {v.lower(): v for v in vocab}
print(f"taxon surface vocabulary: {len(vocab_lc):,}")

lab = pd.read_csv(REPO/"data/training/distill/teacher_labels.csv")
base = pd.read_csv(REPO/"data/training/distill/student_train.csv").reset_index().rename(columns={"index":"row"})
pos = base.merge(lab, on="row").query("label_y == 1") if "label_y" in base.merge(lab,on="row").columns \
      else base.merge(lab,on="row").query("label == 1")
poscol = "label_y" if "label_y" in pos.columns else "label"
print(f"verified positives to build distractors from: {len(pos):,}")

def spans(text_lc, name):
    """character spans of a whole-word occurrence"""
    return [(m.start(), m.end()) for m in re.finditer(r"\b"+re.escape(name.lower())+r"\b", text_lc)]

def overlaps(sp, others):
    return any(not (e2 <= s1 or s2 >= e1) for s1,e1 in sp for s2,e2 in others)

rows=[]; skipped_sub=skipped_ovl=0
for _,r in pos.iterrows():
    text=norm(r.text); tl=text.lower()
    a,b=str(r.source_species), str(r.target_species)
    al,bl=a.lower(), b.lower()
    # character spans occupied by the ORIGINAL pair -- a distractor may not reuse them
    taken = spans(tl,al)+spans(tl,bl)
    others=[]
    for lc,orig in vocab_lc.items():
        if lc in (al,bl): continue
        if len(lc)<5: continue
        # reject names that are a substring of either original taxon, or vice versa
        # (genus inside binomial: "Didelphis" in "Didelphis aurita") -- same clade, not a distractor
        if lc in al or lc in bl or al in lc or bl in lc:
            skipped_sub+=1; continue
        sp=spans(tl,lc)
        if not sp: continue
        # reject if the match sits inside a span already claimed by the pair
        # (species epithet: "micrococcus" inside "Tribulus micrococcus")
        if overlaps(sp,taken):
            skipped_ovl+=1; continue
        others.append(orig)
        if len(others)>=2: break
    for o in others:
        if tuple(sorted([al,o.lower()])) in bpair: continue
        rows.append(dict(text=text, source_species=a, target_species=o,
                         interaction_type=r.interaction_type, kind="distractor"))
print(f"  rejected {skipped_sub:,} substring/same-clade, {skipped_ovl:,} span-overlap candidates")
D=pd.DataFrame(rows).drop_duplicates(subset=["text","source_species","target_species","interaction_type"])
print(f"D. distractor candidates (relation re-targeted at a third taxon in the same passage): {len(D):,}")

out=REPO/"data/training/distill/v4_distractors_to_label.csv"
D.to_csv(out,index=False)
print(f"\nwrote {out}")
print(f"  these go to the teacher for adjudication -- we do NOT assume they are negative.")
print(f"  at 2.3 it/s -> {len(D)/2.3/3600:.1f} GPU-hours")
